exports.all = [
  'JavaScript',
  'AngularJS',
  'HTML5',
  'CSS3',
  'Foundation',
  'Bootstrap',
  'ReactJS',
  'Containerized Apps',
  'Node.js',
  'Express',
  'HIPAA',
  'Amazon Web Services',
  'Scalability',
  'Project Management',
  'Agile',
  'Lambda',
  'PHP',
  'Python',
  'PostgreSQL',
  'MongoDB',
  'REDIS',
  'TDD',
  'MySQL',
  'Progressive Mobile',
  'DynamoDB',
  'Elasticsearch',
  'Server-less Architectures',
];

exports.other = [
  'Amazon Web Services',
  'Containerized Apps',
  'TDD',
  'Server-less Architectures',
  'Progressive Mobile',
];
